# Generated by Django 5.0.6 on 2024-07-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="title",
            field=models.TextField(default=0, max_length=250),
        ),
    ]
