# Generated by Django 5.0.6 on 2024-07-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0002_car_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="title",
            field=models.TextField(default="", max_length=250),
        ),
    ]
