# Generated by Django 5.0.6 on 2024-07-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0004_car_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="title",
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.TextField(max_length=4, null=True),
        ),
    ]
