# Generated by Django 5.0.6 on 2024-07-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0006_publisher_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publisher",
            old_name="addres",
            new_name="address",
        ),
    ]
