# Generated by Django 5.0.6 on 2024-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0007_rename_addres_publisher_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200)),
                ("birth_date", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="authors", to="my_first_app.author"
            ),
        ),
    ]
