# Generated by Django 5.0.6 on 2024-07-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0009_profiel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profiel",
            new_name="Profile",
        ),
    ]
